version: "3"

services:
  veramo_remote_agente:
    build: .
    ports:
      - "3336:3336"
    env_file:
      - .env
    command: [ "yarn", "veramo", "server", "--config=/config/agent.yml" ]
    volumes:
      - ./config:/config
      - .:/usr/src/app
